### ISSUE TITLE
sponsor_image gets hidden by ad blockers

### ISSUE THREAD

**Issue by sloria** [typlog/sphinx-typlog-theme#12]
Sponsor images with the `sponsor_image` class get hidden by uBlock origin.

uBlock on:

![image](https://user-images.githubusercontent.com/2379650/50527425-3588e380-0ab6-11e9-8aca-028b60bf7348.png)

uBlock off:

![image](https://user-images.githubusercontent.com/2379650/50527409-22761380-0ab6-11e9-8952-beb8a64cc6d8.png)

Looks like uBlock adds `display: none important!` to elements that have that class.

**Comment by sloria** [comment]
I was able to work around the issue by using a [different class](https://github.com/marshmallow-code/webargs/pull/348/files#diff-74e177210b904b89b86ce2ab4416e29fR4) (`.logo`) for the sponsor image, along with some [extra css](https://github.com/marshmallow-code/webargs/pull/348/files#diff-53bc4d85d069df2dd18ae4972ddbee46R1).

**Comment by lepture** [comment]
Fixed in https://github.com/typlog/sphinx-typlog-theme/commit/784aeaa3576eaf30b0433f2d7a8b0e37ad0dab87

**Comment by sloria** [comment]
Thanks! I was able to remove my workaround after installing 0.7.1.
