### ISSUE TITLE
Does not work properly with `sphinx_autodoc_typehints`

### ISSUE THREAD

**Issue by sobolevn** [typlog/sphinx-typlog-theme#15]
Hi, thanks for this awesome theme.
I have tried it for the very first time for my new project: https://dry-monads.readthedocs.io/en/latest/
It works pretty great except some minor bugs I have found.

The most important one is: it does not work correctly with [`sphinx_autodoc_typehints`](https://github.com/agronholm/sphinx-autodoc-typehints).

That's what it produces: https://dry-monads.readthedocs.io/en/latest/pages/either.html#dry_monads.either.Left
<img width="794" alt="2019-01-28 14 52 04" src="https://user-images.githubusercontent.com/4660275/51834744-4e322680-230c-11e9-90b8-4a72203dbe2e.png">

But, as you can see from the [sourcecode](https://dry-monads.readthedocs.io/en/latest/_modules/dry_monads/either.html#Left) I have typed parameters in the `value_or` method: 

```python
def value_or(self, default_value: NewValueType) -> NewValueType:
        """Returns the value if we deal with 'Right' or default if 'Left'."""
        return default_value
```

But, none parameter annotations are showed up. Only return type annotations are shown.

**Comment by lepture** [comment]
Hi @sobolevn 

I don't have any experience with sphinx_autodoc_typehints. Can you add an example in this theme's docs: https://github.com/typlog/sphinx-typlog-theme/tree/master/docs

If there is an example, I can fix it quickly.

**Comment by sobolevn** [comment]
@lepture thanks for your response! I have an open-source project setup that is using both: https://github.com/dry-python/returns

Docs: https://returns.readthedocs.io/en/latest/

**Comment by lepture** [comment]
@sobolevn sorry, I tried but failed to build your documentation. I can't figure out how to build the documentation of your project.

Could you add a **simple** example for me?

**Comment by chrizzFTD** [comment]
I had a similar doubt and realized that the parameter annotations properly showed up after adding this configuration option on [`sphinx-autodoc-typehint` options](https://github.com/agronholm/sphinx-autodoc-typehints#options):

```python
always_document_param_types = True
```

With this, the annotations on my project were showing as expected. This [seems to be the same fix](https://github.com/dry-python/returns/commit/d550878379434b0e4eb011d56ac10bf2c0e6ff9f#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3R79) for you, @sobolevn; could you confirm you no longer have the issue, please? :P

**Comment by sobolevn** [comment]
Yes!
