### ISSUE TITLE
Search does not work properly

### ISSUE THREAD

**Issue by sobolevn** [typlog/sphinx-typlog-theme#16]
Related #15 

I have also found that search does not work.
Here's an example from another project.

Try to search for `django`:
https://webargs.readthedocs.io/en/latest/search.html?q=django&check_keywords=yes&area=default

No results.
But, we can clearly see the word "Django" on the very first page: https://webargs.readthedocs.io/en/latest/
Actually, no queries work at all.

**Comment by lepture** [comment]
It should include a `searchtools.js` in search page. I need to find out why it is not included.

**Comment by lepture** [comment]
@sobolevn it is fixed. Please update to 0.7.2
