### ISSUE TITLE
Use sphinx-issues?

### ISSUE THREAD

**Issue by sloria** [typlog/sphinx-typlog-theme#8]
I see that this project has its own `:gh:` role. You might consider using [sphinx-issues](https://github.com/sloria/sphinx-issues) (full disclosure: I'm the author), which supports linking to GitHub issues with `:issue:`, PRs with `:pr:`, and users with `:user:`. ~~Commits aren't supported yet, but I've [opened an issue](https://github.com/sloria/sphinx-issues/issues/64)~~.

Just a minor suggestion. Feel free to close if you're not interested.

EDIT: Linking to commits is now supported.

**Comment by lepture** [comment]
They are compatible. The theme won’t add any role automatically, people need to use them specifically. In this case, people can choose to use sphinx-issue.

**Comment by sloria** [comment]
Fair enough. I see now that users need to call `add_github_roles`. No action needed here, so closing.
